[general]
bars = 12
framerate = 20
[input]
method = pulse
source = auto
[smoothing]
noise_reduction = 60
[output]
method = raw
raw_target = /dev/stdout
data_format = ascii
ascii_max_range = 100
bar_delimiter = 59
frame_delimiter = 10
